### ISSUE TITLE
CSV support

### ISSUE THREAD

**Issue by pdurbin** [ukdataservice/qamd#7]
Hello! I believe I first heard about QAMyData from @janetm in April and I just took another look after seeing QAMyData and Dataverse mentioned in the same slide at https://twitter.com/alina_danciu_/status/1177496046181634048

![EFdOaRwUUAAgbOw](https://user-images.githubusercontent.com/21006/65761521-eb886900-e0ec-11e9-9df1-b2d0ef28e8eb.jpg)

As a developer, I came to this GitHub repo first and saw from the description that QAMyData has support for three proprietary formats (SPSS, STATA and SAS):

<img width="541" alt="Screen Shot 2019-09-27 at 6 02 58 AM" src="https://user-images.githubusercontent.com/21006/65761626-2ab6ba00-e0ed-11e9-8e96-33656eb3f7d9.png">

I was a little sad that CSV isn't supported (I also checked the README and the wiki) but from looking at https://www.ukdataservice.ac.uk/about-us/our-rd/qamydata.aspx I see that CSV is supported! 🎉 🎉 

<img width="510" alt="Screen Shot 2019-09-27 at 6 00 48 AM" src="https://user-images.githubusercontent.com/21006/65761637-31ddc800-e0ed-11e9-87cd-613ece5a3c09.png">

I think the fix here in GitHub is pretty easy. I would suggest mentioning CSV (and all formats you support) in the description and the README.

**Comment by Lyrain** [comment]
Absolutely! I'll make sure to update the REAEME and description accordingly. 

CSV is supported differently and hasn't been a primary focus, due to the lack of metadata that can be attached to a CSV file compared with the other formats.

Thanks for opening the issue!
