### ISSUE TITLE
Cannot compile qamd

### ISSUE THREAD

**Issue by sefnyn** [ukdataservice/qamd#8]
ns@bach ~/q/qamd> **cargo build --release**
   Compiling qamd v1.0.0 (/home/ns/qamd/qamd)
error[E0502]: cannot borrow `*context` as mutable because `context.variables` is also borrowed as immutable
   --> src/check/post.rs:188:16
    |
174 |     for variable in context.variables.iter()
    |                     ----------------- immutable borrow occurs here
...
188 |     dictionary(context, ValueLabelSpellcheck, &words, spellcheck_predicate);
    |                ^^^^^^^ mutable borrow occurs here
189 | }
    | - immutable borrow ends here

error: aborting due to previous error

**Comment by Lyrain** [comment]
Could I get your rustc version from `rustc --version`, I've seen this exact error before and it was related to a the rustc version.

I have success compiling on rustc 1.37.0 (eae3437df 2019-08-13). If your rustc version is older, you can update the rust toolchain with `rustup update`.

**Comment by sefnyn** [comment]
Thanks!  Yes, my rustc was 1.34 but I upgraded to 1.37.  Just a few warnings for future reference:

   Compiling qamd v1.0.0 (/home/ns/qamd/qamd)
warning: trait objects without an explicit `dyn` are deprecated
   --> src/report/html/mod.rs:104:60
    |
104 | fn locators_table<'a>(name: String, status: Status) -> Box<RenderBox> {
    |                                                            ^^^^^^^^^ help: use `dyn`: `dyn RenderBox`
    |
    = note: #[warn(bare_trait_objects)] on by default

warning: trait objects without an explicit `dyn` are deprecated
   --> src/report/html/mod.rs:128:64
    |
128 | fn value_if_positive(value: i32, default: &'static str) -> Box<Render> {
    |                                                                ^^^^^^ help: use `dyn`: `dyn Render`

warning: trait objects without an explicit `dyn` are deprecated
   --> src/report/html/mod.rs:145:18
    |
145 | fn logo() -> Box<RenderBox + 'static> {
    |                  ^^^^^^^^^^^^^^^^^^^ help: use `dyn`: `dyn RenderBox + 'static`

warning: trait objects without an explicit `dyn` are deprecated
   --> src/report/html/mod.rs:208:48
    |
208 | fn metadata<'a>(metadata: &'a Metadata) -> Box<RenderBox + 'a> {
    |                                                ^^^^^^^^^^^^^^ help: use `dyn`: `dyn RenderBox + 'a`

    Finished release [optimized] target(s) in 6m 52s
ns@bach ~/q/qamd>

**Comment by Lyrain** [comment]
Grand! Glad I could be of assistance.
